//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maks
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int ID { get; set; }
        public Nullable<int> Num_lesson { get; set; }
        public Nullable<int> Classes_id { get; set; }
        public Nullable<int> Items_id { get; set; }
        public Nullable<int> DayWeek_id { get; set; }
    
        public virtual Classes Classes { get; set; }
        public virtual DayWeek DayWeek { get; set; }
        public virtual Items Items { get; set; }
    }
}
